#!/usr/bin/env node
// Rebuild docs/knowledge/INDEX.md from per-entry frontmatter.
// Idempotent. Stable order. No deps.
//
// Usage: node rebuild-index.mjs <project-root>

import fs from 'node:fs';
import path from 'node:path';

const projectRoot = process.argv[2];
if (!projectRoot) {
  console.error('Usage: rebuild-index.mjs <project-root>');
  process.exit(1);
}

const kbRoot = path.join(projectRoot, 'docs', 'knowledge');
if (!fs.existsSync(kbRoot)) {
  console.log('no KB found; nothing to index');
  process.exit(0);
}

const TYPES = ['gotchas', 'decisions', 'conventions', 'ground-truth', 'references', 'patterns'];

// ----- frontmatter extraction (regex-based, schema-specific) ----------------

function extractFrontmatter(content) {
  const m = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  return m ? m[1] : '';
}

function scalarField(fm, key) {
  const m = fm.match(new RegExp(`^${key}:\\s*(.+?)\\s*$`, 'm'));
  return m ? m[1].trim().replace(/^['"]|['"]$/g, '') : null;
}

// Parse a list field that may be inline `key: [a, b]` or block:
//   key:
//     - a
//     - b
function listField(fm, key) {
  const inline = fm.match(new RegExp(`^${key}:\\s*\\[(.*?)\\]\\s*$`, 'm'));
  if (inline) {
    return inline[1]
      .split(',')
      .map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
      .filter(Boolean);
  }
  const block = fm.match(new RegExp(`^${key}:\\s*\\n((?:\\s+-\\s+.+\\n?)+)`, 'm'));
  if (block) {
    return block[1]
      .split(/\r?\n/)
      .map((line) => line.match(/^\s+-\s+(.+?)\s*$/)?.[1])
      .filter(Boolean)
      .map((s) => s.replace(/^['"]|['"]$/g, ''));
  }
  return [];
}

// Parse `applies-to.<sub>` — the field is a nested object whose value is
// either a list block or an inline list. Capture every indented line
// (≥1 leading space/tab + non-whitespace) until the first non-indented
// line OR end of frontmatter.
function appliesTo(fm, sub) {
  const m = fm.match(/^applies-to:\s*\n((?:[ \t]+\S.*\n?)+)/m);
  if (!m) return [];
  const block = m[1];
  return listField(block.replace(/^[ \t]+/gm, ''), sub);
}

function extractTitle(content) {
  const body = content.replace(/^---[\s\S]*?\n---\s*\n?/, '');
  const m = body.match(/^#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : '<untitled>';
}

// ----- manifest -------------------------------------------------------------

function readManifest() {
  const manifestPath = path.join(kbRoot, 'manifest.yaml');
  if (!fs.existsSync(manifestPath)) {
    return { name: path.basename(projectRoot) };
  }
  const content = fs.readFileSync(manifestPath, 'utf8');
  // Match `name:` under `project:` block. Quick regex (no full YAML parse).
  const nameMatch = content.match(/^\s+name:\s*(.+?)\s*$/m);
  return {
    name: nameMatch ? nameMatch[1].trim().replace(/^['"]|['"]$/g, '') : path.basename(projectRoot),
  };
}

// ----- entry collection -----------------------------------------------------

function collectEntries() {
  const entries = [];
  let supersededHidden = 0;

  for (const type of TYPES) {
    const typeDir = path.join(kbRoot, type);
    if (!fs.existsSync(typeDir)) continue;
    const files = fs.readdirSync(typeDir).filter((f) => f.endsWith('.md'));
    for (const file of files) {
      const filePath = path.join(typeDir, file);
      const content = fs.readFileSync(filePath, 'utf8');
      const fm = extractFrontmatter(content);
      const freshness = scalarField(fm, 'freshness') || '<missing>';
      if (freshness === 'superseded') {
        supersededHidden++;
        continue;
      }
      entries.push({
        type,
        relPath: `${type}/${file}`,
        title: extractTitle(content),
        freshness,
        lastValidated: scalarField(fm, 'last-validated') || '<missing>',
        tools: appliesTo(fm, 'tools'),
        domains: appliesTo(fm, 'domains'),
      });
    }
    // Also count anything in <type>/_superseded/
    const supersededDir = path.join(typeDir, '_superseded');
    if (fs.existsSync(supersededDir)) {
      supersededHidden += fs.readdirSync(supersededDir).filter((f) => f.endsWith('.md')).length;
    }
  }

  return { entries, supersededHidden };
}

// ----- index generation -----------------------------------------------------

function generateIndex(manifest, { entries, supersededHidden }) {
  const grouped = {};
  for (const type of TYPES) grouped[type] = [];
  for (const e of entries) grouped[e.type].push(e);
  for (const type of TYPES) grouped[type].sort((a, b) => a.relPath.localeCompare(b.relPath));

  const lines = [];
  lines.push(`# Knowledge Index — ${manifest.name}`);
  lines.push('');
  lines.push('> Auto-generated by `rebuild-index`. Do not edit by hand — changes will be overwritten.');
  lines.push(`> Last regenerated: ${new Date().toISOString()}`);
  lines.push(`> Total entries: ${entries.length}  ·  Superseded (hidden): ${supersededHidden}`);
  lines.push('');

  for (const type of TYPES) {
    const items = grouped[type];
    lines.push(`## ${type} (${items.length})`);
    lines.push('');
    if (items.length === 0) {
      lines.push('_(none)_');
      lines.push('');
      continue;
    }
    for (const it of items) {
      const tools = it.tools.length ? `\`${it.tools.join(', ')}\`` : '`-`';
      const domains = it.domains.length ? `\`${it.domains.join(', ')}\`` : '`-`';
      lines.push(
        `- [${it.title}](${it.relPath}) — \`${it.freshness}\` · last-validated ${it.lastValidated} · tools ${tools} · domains ${domains}`,
      );
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ----- main -----------------------------------------------------------------

const manifest = readManifest();
const { entries, supersededHidden } = collectEntries();
const indexContent = generateIndex(manifest, { entries, supersededHidden });
fs.writeFileSync(path.join(kbRoot, 'INDEX.md'), indexContent, 'utf8');
console.log(`INDEX rebuilt: ${entries.length} entries (${supersededHidden} superseded hidden)`);
